<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regencies = [
            array('id' => '1101','province_id' => '11','name' => 'KAB. ACEH SELATAN'),
            array('id' => '1102','province_id' => '11','name' => 'KAB. ACEH TENGGARA'),
            array('id' => '1103','province_id' => '11','name' => 'KAB. ACEH TIMUR'),
            array('id' => '1104','province_id' => '11','name' => 'KAB. ACEH TENGAH'),
            array('id' => '1105','province_id' => '11','name' => 'KAB. ACEH BARAT'),
            array('id' => '1106','province_id' => '11','name' => 'KAB. ACEH BESAR'),
            array('id' => '1107','province_id' => '11','name' => 'KAB. PIDIE'),
            array('id' => '1108','province_id' => '11','name' => 'KAB. ACEH UTARA'),
            array('id' => '1109','province_id' => '11','name' => 'KAB. SIMEULUE'),
            array('id' => '1110','province_id' => '11','name' => 'KAB. ACEH SINGKIL'),
            array('id' => '1111','province_id' => '11','name' => 'KAB. BIREUEN'),
            array('id' => '1112','province_id' => '11','name' => 'KAB. ACEH BARAT DAYA'),
            array('id' => '1113','province_id' => '11','name' => 'KAB. GAYO LUES'),
            array('id' => '1114','province_id' => '11','name' => 'KAB. ACEH JAYA'),
            array('id' => '1115','province_id' => '11','name' => 'KAB. NAGAN RAYA'),
            array('id' => '1116','province_id' => '11','name' => 'KAB. ACEH TAMIANG'),
            array('id' => '1117','province_id' => '11','name' => 'KAB. BENER MERIAH'),
            array('id' => '1118','province_id' => '11','name' => 'KAB. PIDIE JAYA'),
            array('id' => '1171','province_id' => '11','name' => 'KOTA BANDA ACEH'),
            array('id' => '1172','province_id' => '11','name' => 'KOTA SABANG'),
            array('id' => '1173','province_id' => '11','name' => 'KOTA LHOKSEUMAWE'),
            array('id' => '1174','province_id' => '11','name' => 'KOTA LANGSA'),
            array('id' => '1175','province_id' => '11','name' => 'KOTA SUBULUSSALAM'),
            array('id' => '1201','province_id' => '12','name' => 'KAB. TAPANULI TENGAH'),
            array('id' => '1202','province_id' => '12','name' => 'KAB. TAPANULI UTARA'),
            array('id' => '1203','province_id' => '12','name' => 'KAB. TAPANULI SELATAN'),
            array('id' => '1204','province_id' => '12','name' => 'KAB. NIAS'),
            array('id' => '1205','province_id' => '12','name' => 'KAB. LANGKAT'),
            array('id' => '1206','province_id' => '12','name' => 'KAB. KARO'),
            array('id' => '1207','province_id' => '12','name' => 'KAB. DELI SERDANG'),
            array('id' => '1208','province_id' => '12','name' => 'KAB. SIMALUNGUN'),
            array('id' => '1209','province_id' => '12','name' => 'KAB. ASAHAN'),
            array('id' => '1210','province_id' => '12','name' => 'KAB. LABUHANBATU'),
            array('id' => '1211','province_id' => '12','name' => 'KAB. DAIRI'),
            array('id' => '1212','province_id' => '12','name' => 'KAB. TOBA'),
            array('id' => '1213','province_id' => '12','name' => 'KAB. MANDAILING NATAL'),
            array('id' => '1214','province_id' => '12','name' => 'KAB. NIAS SELATAN'),
            array('id' => '1215','province_id' => '12','name' => 'KAB. PAKPAK BHARAT'),
            array('id' => '1216','province_id' => '12','name' => 'KAB. HUMBANG HASUNDUTAN'),
            array('id' => '1217','province_id' => '12','name' => 'KAB. SAMOSIR'),
            array('id' => '1218','province_id' => '12','name' => 'KAB. SERDANG BEDAGAI'),
            array('id' => '1219','province_id' => '12','name' => 'KAB. BATU BARA'),
            array('id' => '1220','province_id' => '12','name' => 'KAB. PADANG LAWAS UTARA'),
            array('id' => '1221','province_id' => '12','name' => 'KAB. PADANG LAWAS'),
            array('id' => '1222','province_id' => '12','name' => 'KAB. LABUHANBATU SELATAN'),
            array('id' => '1223','province_id' => '12','name' => 'KAB. LABUHANBATU UTARA'),
            array('id' => '1224','province_id' => '12','name' => 'KAB. NIAS UTARA'),
            array('id' => '1225','province_id' => '12','name' => 'KAB. NIAS BARAT'),
            array('id' => '1271','province_id' => '12','name' => 'KOTA MEDAN'),
            array('id' => '1272','province_id' => '12','name' => 'KOTA PEMATANGSIANTAR'),
            array('id' => '1273','province_id' => '12','name' => 'KOTA SIBOLGA'),
            array('id' => '1274','province_id' => '12','name' => 'KOTA TANJUNG BALAI'),
            array('id' => '1275','province_id' => '12','name' => 'KOTA BINJAI'),
            array('id' => '1276','province_id' => '12','name' => 'KOTA TEBING TINGGI'),
            array('id' => '1277','province_id' => '12','name' => 'KOTA PADANGSIDIMPUAN'),
            array('id' => '1278','province_id' => '12','name' => 'KOTA GUNUNGSITOLI'),
            array('id' => '1301','province_id' => '13','name' => 'KAB. PESISIR SELATAN'),
            array('id' => '1302','province_id' => '13','name' => 'KAB. SOLOK'),
            array('id' => '1303','province_id' => '13','name' => 'KAB. SIJUNJUNG'),
            array('id' => '1304','province_id' => '13','name' => 'KAB. TANAH DATAR'),
            array('id' => '1305','province_id' => '13','name' => 'KAB. PADANG PARIAMAN'),
            array('id' => '1306','province_id' => '13','name' => 'KAB. AGAM'),
            array('id' => '1307','province_id' => '13','name' => 'KAB. LIMA PULUH KOTA'),
            array('id' => '1308','province_id' => '13','name' => 'KAB. PASAMAN'),
            array('id' => '1309','province_id' => '13','name' => 'KAB. KEPULAUAN MENTAWAI'),
            array('id' => '1310','province_id' => '13','name' => 'KAB. DHARMASRAYA'),
            array('id' => '1311','province_id' => '13','name' => 'KAB. SOLOK SELATAN'),
            array('id' => '1312','province_id' => '13','name' => 'KAB. PASAMAN BARAT'),
            array('id' => '1371','province_id' => '13','name' => 'KOTA PADANG'),
            array('id' => '1372','province_id' => '13','name' => 'KOTA SOLOK'),
            array('id' => '1373','province_id' => '13','name' => 'KOTA SAWAHLUNTO'),
            array('id' => '1374','province_id' => '13','name' => 'KOTA PADANG PANJANG'),
            array('id' => '1375','province_id' => '13','name' => 'KOTA BUKITTINGGI'),
            array('id' => '1376','province_id' => '13','name' => 'KOTA PAYAKUMBUH'),
            array('id' => '1377','province_id' => '13','name' => 'KOTA PARIAMAN'),
            array('id' => '1401','province_id' => '14','name' => 'KAB. KAMPAR'),
            array('id' => '1402','province_id' => '14','name' => 'KAB. INDRAGIRI HULU'),
            array('id' => '1403','province_id' => '14','name' => 'KAB. BENGKALIS'),
            array('id' => '1404','province_id' => '14','name' => 'KAB. INDRAGIRI HILIR'),
            array('id' => '1405','province_id' => '14','name' => 'KAB. PELALAWAN'),
            array('id' => '1406','province_id' => '14','name' => 'KAB. ROKAN HULU'),
            array('id' => '1407','province_id' => '14','name' => 'KAB. ROKAN HILIR'),
            array('id' => '1408','province_id' => '14','name' => 'KAB. SIAK'),
            array('id' => '1409','province_id' => '14','name' => 'KAB. KUANTAN SINGINGI'),
            array('id' => '1410','province_id' => '14','name' => 'KAB. KEPULAUAN MERANTI'),
            array('id' => '1471','province_id' => '14','name' => 'KOTA PEKANBARU'),
            array('id' => '1472','province_id' => '14','name' => 'KOTA DUMAI'),
            array('id' => '1501','province_id' => '15','name' => 'KAB. KERINCI'),
            array('id' => '1502','province_id' => '15','name' => 'KAB. MERANGIN'),
            array('id' => '1503','province_id' => '15','name' => 'KAB. SAROLANGUN'),
            array('id' => '1504','province_id' => '15','name' => 'KAB. BATANGHARI'),
            array('id' => '1505','province_id' => '15','name' => 'KAB. MUARO JAMBI'),
            array('id' => '1506','province_id' => '15','name' => 'KAB. TANJUNG JABUNG BARAT'),
            array('id' => '1507','province_id' => '15','name' => 'KAB. TANJUNG JABUNG TIMUR'),
            array('id' => '1508','province_id' => '15','name' => 'KAB. BUNGO'),
            array('id' => '1509','province_id' => '15','name' => 'KAB. TEBO'),
            array('id' => '1571','province_id' => '15','name' => 'KOTA JAMBI'),
            array('id' => '1572','province_id' => '15','name' => 'KOTA SUNGAI PENUH'),
            array('id' => '1601','province_id' => '16','name' => 'KAB. OGAN KOMERING ULU'),
            array('id' => '1602','province_id' => '16','name' => 'KAB. OGAN KOMERING ILIR'),
            array('id' => '1603','province_id' => '16','name' => 'KAB. MUARA ENIM'),
            array('id' => '1604','province_id' => '16','name' => 'KAB. LAHAT'),
            array('id' => '1605','province_id' => '16','name' => 'KAB. MUSI RAWAS'),
            array('id' => '1606','province_id' => '16','name' => 'KAB. MUSI BANYUASIN'),
            array('id' => '1607','province_id' => '16','name' => 'KAB. BANYUASIN'),
            array('id' => '1608','province_id' => '16','name' => 'KAB. OGAN KOMERING ULU TIMUR'),
            array('id' => '1609','province_id' => '16','name' => 'KAB. OGAN KOMERING ULU SELATAN'),
            array('id' => '1610','province_id' => '16','name' => 'KAB. OGAN ILIR'),
            array('id' => '1611','province_id' => '16','name' => 'KAB. EMPAT LAWANG'),
            array('id' => '1612','province_id' => '16','name' => 'KAB. PENUKAL ABAB LEMATANG ILIR'),
            array('id' => '1613','province_id' => '16','name' => 'KAB. MUSI RAWAS UTARA'),
            array('id' => '1671','province_id' => '16','name' => 'KOTA PALEMBANG'),
            array('id' => '1672','province_id' => '16','name' => 'KOTA PAGAR ALAM'),
            array('id' => '1673','province_id' => '16','name' => 'KOTA LUBUK LINGGAU'),
            array('id' => '1674','province_id' => '16','name' => 'KOTA PRABUMULIH'),
            array('id' => '1701','province_id' => '17','name' => 'KAB. BENGKULU SELATAN'),
            array('id' => '1702','province_id' => '17','name' => 'KAB. REJANG LEBONG'),
            array('id' => '1703','province_id' => '17','name' => 'KAB. BENGKULU UTARA'),
            array('id' => '1704','province_id' => '17','name' => 'KAB. KAUR'),
            array('id' => '1705','province_id' => '17','name' => 'KAB. SELUMA'),
            array('id' => '1706','province_id' => '17','name' => 'KAB. MUKO MUKO'),
            array('id' => '1707','province_id' => '17','name' => 'KAB. LEBONG'),
            array('id' => '1708','province_id' => '17','name' => 'KAB. KEPAHIANG'),
            array('id' => '1709','province_id' => '17','name' => 'KAB. BENGKULU TENGAH'),
            array('id' => '1771','province_id' => '17','name' => 'KOTA BENGKULU'),
            array('id' => '1801','province_id' => '18','name' => 'KAB. LAMPUNG SELATAN'),
            array('id' => '1802','province_id' => '18','name' => 'KAB. LAMPUNG TENGAH'),
            array('id' => '1803','province_id' => '18','name' => 'KAB. LAMPUNG UTARA'),
            array('id' => '1804','province_id' => '18','name' => 'KAB. LAMPUNG BARAT'),
            array('id' => '1805','province_id' => '18','name' => 'KAB. TULANG BAWANG'),
            array('id' => '1806','province_id' => '18','name' => 'KAB. TANGGAMUS'),
            array('id' => '1807','province_id' => '18','name' => 'KAB. LAMPUNG TIMUR'),
            array('id' => '1808','province_id' => '18','name' => 'KAB. WAY KANAN'),
            array('id' => '1809','province_id' => '18','name' => 'KAB. PESAWARAN'),
            array('id' => '1810','province_id' => '18','name' => 'KAB. PRINGSEWU'),
            array('id' => '1811','province_id' => '18','name' => 'KAB. MESUJI'),
            array('id' => '1812','province_id' => '18','name' => 'KAB. TULANG BAWANG BARAT'),
            array('id' => '1813','province_id' => '18','name' => 'KAB. PESISIR BARAT'),
            array('id' => '1871','province_id' => '18','name' => 'KOTA BANDAR LAMPUNG'),
            array('id' => '1872','province_id' => '18','name' => 'KOTA METRO'),
            array('id' => '1901','province_id' => '19','name' => 'KAB. BANGKA'),
            array('id' => '1902','province_id' => '19','name' => 'KAB. BELITUNG'),
            array('id' => '1903','province_id' => '19','name' => 'KAB. BANGKA SELATAN'),
            array('id' => '1904','province_id' => '19','name' => 'KAB. BANGKA TENGAH'),
            array('id' => '1905','province_id' => '19','name' => 'KAB. BANGKA BARAT'),
            array('id' => '1906','province_id' => '19','name' => 'KAB. BELITUNG TIMUR'),
            array('id' => '1971','province_id' => '19','name' => 'KOTA PANGKAL PINANG'),
            array('id' => '2101','province_id' => '21','name' => 'KAB. BINTAN'),
            array('id' => '2102','province_id' => '21','name' => 'KAB. KARIMUN'),
            array('id' => '2103','province_id' => '21','name' => 'KAB. NATUNA'),
            array('id' => '2104','province_id' => '21','name' => 'KAB. LINGGA'),
            array('id' => '2105','province_id' => '21','name' => 'KAB. KEPULAUAN ANAMBAS'),
            array('id' => '2171','province_id' => '21','name' => 'KOTA BATAM'),
            array('id' => '2172','province_id' => '21','name' => 'KOTA TANJUNG PINANG'),
            array('id' => '3101','province_id' => '31','name' => 'KAB. ADM. KEP. SERIBU'),
            array('id' => '3171','province_id' => '31','name' => 'KOTA ADM. JAKARTA PUSAT'),
            array('id' => '3172','province_id' => '31','name' => 'KOTA ADM. JAKARTA UTARA'),
            array('id' => '3173','province_id' => '31','name' => 'KOTA ADM. JAKARTA BARAT'),
            array('id' => '3174','province_id' => '31','name' => 'KOTA ADM. JAKARTA SELATAN'),
            array('id' => '3175','province_id' => '31','name' => 'KOTA ADM. JAKARTA TIMUR'),
            array('id' => '3201','province_id' => '32','name' => 'KAB. BOGOR'),
            array('id' => '3202','province_id' => '32','name' => 'KAB. SUKABUMI'),
            array('id' => '3203','province_id' => '32','name' => 'KAB. CIANJUR'),
            array('id' => '3204','province_id' => '32','name' => 'KAB. BANDUNG'),
            array('id' => '3205','province_id' => '32','name' => 'KAB. GARUT'),
            array('id' => '3206','province_id' => '32','name' => 'KAB. TASIKMALAYA'),
            array('id' => '3207','province_id' => '32','name' => 'KAB. CIAMIS'),
            array('id' => '3208','province_id' => '32','name' => 'KAB. KUNINGAN'),
            array('id' => '3209','province_id' => '32','name' => 'KAB. CIREBON'),
            array('id' => '3210','province_id' => '32','name' => 'KAB. MAJALENGKA'),
            array('id' => '3211','province_id' => '32','name' => 'KAB. SUMEDANG'),
            array('id' => '3212','province_id' => '32','name' => 'KAB. INDRAMAYU'),
            array('id' => '3213','province_id' => '32','name' => 'KAB. SUBANG'),
            array('id' => '3214','province_id' => '32','name' => 'KAB. PURWAKARTA'),
            array('id' => '3215','province_id' => '32','name' => 'KAB. KARAWANG'),
            array('id' => '3216','province_id' => '32','name' => 'KAB. BEKASI'),
            array('id' => '3217','province_id' => '32','name' => 'KAB. BANDUNG BARAT'),
            array('id' => '3218','province_id' => '32','name' => 'KAB. PANGANDARAN'),
            array('id' => '3271','province_id' => '32','name' => 'KOTA BOGOR'),
            array('id' => '3272','province_id' => '32','name' => 'KOTA SUKABUMI'),
            array('id' => '3273','province_id' => '32','name' => 'KOTA BANDUNG'),
            array('id' => '3274','province_id' => '32','name' => 'KOTA CIREBON'),
            array('id' => '3275','province_id' => '32','name' => 'KOTA BEKASI'),
            array('id' => '3276','province_id' => '32','name' => 'KOTA DEPOK'),
            array('id' => '3277','province_id' => '32','name' => 'KOTA CIMAHI'),
            array('id' => '3278','province_id' => '32','name' => 'KOTA TASIKMALAYA'),
            array('id' => '3279','province_id' => '32','name' => 'KOTA BANJAR'),
            array('id' => '3301','province_id' => '33','name' => 'KAB. CILACAP'),
            array('id' => '3302','province_id' => '33','name' => 'KAB. BANYUMAS'),
            array('id' => '3303','province_id' => '33','name' => 'KAB. PURBALINGGA'),
            array('id' => '3304','province_id' => '33','name' => 'KAB. BANJARNEGARA'),
            array('id' => '3305','province_id' => '33','name' => 'KAB. KEBUMEN'),
            array('id' => '3306','province_id' => '33','name' => 'KAB. PURWOREJO'),
            array('id' => '3307','province_id' => '33','name' => 'KAB. WONOSOBO'),
            array('id' => '3308','province_id' => '33','name' => 'KAB. MAGELANG'),
            array('id' => '3309','province_id' => '33','name' => 'KAB. BOYOLALI'),
            array('id' => '3310','province_id' => '33','name' => 'KAB. KLATEN'),
            array('id' => '3311','province_id' => '33','name' => 'KAB. SUKOHARJO'),
            array('id' => '3312','province_id' => '33','name' => 'KAB. WONOGIRI'),
            array('id' => '3313','province_id' => '33','name' => 'KAB. KARANGANYAR'),
            array('id' => '3314','province_id' => '33','name' => 'KAB. SRAGEN'),
            array('id' => '3315','province_id' => '33','name' => 'KAB. GROBOGAN'),
            array('id' => '3316','province_id' => '33','name' => 'KAB. BLORA'),
            array('id' => '3317','province_id' => '33','name' => 'KAB. REMBANG'),
            array('id' => '3318','province_id' => '33','name' => 'KAB. PATI'),
            array('id' => '3319','province_id' => '33','name' => 'KAB. KUDUS'),
            array('id' => '3320','province_id' => '33','name' => 'KAB. JEPARA'),
            array('id' => '3321','province_id' => '33','name' => 'KAB. DEMAK'),
            array('id' => '3322','province_id' => '33','name' => 'KAB. SEMARANG'),
            array('id' => '3323','province_id' => '33','name' => 'KAB. TEMANGGUNG'),
            array('id' => '3324','province_id' => '33','name' => 'KAB. KENDAL'),
            array('id' => '3325','province_id' => '33','name' => 'KAB. BATANG'),
            array('id' => '3326','province_id' => '33','name' => 'KAB. PEKALONGAN'),
            array('id' => '3327','province_id' => '33','name' => 'KAB. PEMALANG'),
            array('id' => '3328','province_id' => '33','name' => 'KAB. TEGAL'),
            array('id' => '3329','province_id' => '33','name' => 'KAB. BREBES'),
            array('id' => '3371','province_id' => '33','name' => 'KOTA MAGELANG'),
            array('id' => '3372','province_id' => '33','name' => 'KOTA SURAKARTA'),
            array('id' => '3373','province_id' => '33','name' => 'KOTA SALATIGA'),
            array('id' => '3374','province_id' => '33','name' => 'KOTA SEMARANG'),
            array('id' => '3375','province_id' => '33','name' => 'KOTA PEKALONGAN'),
            array('id' => '3376','province_id' => '33','name' => 'KOTA TEGAL'),
            array('id' => '3401','province_id' => '34','name' => 'KAB. KULON PROGO'),
            array('id' => '3402','province_id' => '34','name' => 'KAB. BANTUL'),
            array('id' => '3403','province_id' => '34','name' => 'KAB. GUNUNGKIDUL'),
            array('id' => '3404','province_id' => '34','name' => 'KAB. SLEMAN'),
            array('id' => '3471','province_id' => '34','name' => 'KOTA YOGYAKARTA'),
            array('id' => '3501','province_id' => '35','name' => 'KAB. PACITAN'),
            array('id' => '3502','province_id' => '35','name' => 'KAB. PONOROGO'),
            array('id' => '3503','province_id' => '35','name' => 'KAB. TRENGGALEK'),
            array('id' => '3504','province_id' => '35','name' => 'KAB. TULUNGAGUNG'),
            array('id' => '3505','province_id' => '35','name' => 'KAB. BLITAR'),
            array('id' => '3506','province_id' => '35','name' => 'KAB. KEDIRI'),
            array('id' => '3507','province_id' => '35','name' => 'KAB. MALANG'),
            array('id' => '3508','province_id' => '35','name' => 'KAB. LUMAJANG'),
            array('id' => '3509','province_id' => '35','name' => 'KAB. JEMBER'),
            array('id' => '3510','province_id' => '35','name' => 'KAB. BANYUWANGI'),
            array('id' => '3511','province_id' => '35','name' => 'KAB. BONDOWOSO'),
            array('id' => '3512','province_id' => '35','name' => 'KAB. SITUBONDO'),
            array('id' => '3513','province_id' => '35','name' => 'KAB. PROBOLINGGO'),
            array('id' => '3514','province_id' => '35','name' => 'KAB. PASURUAN'),
            array('id' => '3515','province_id' => '35','name' => 'KAB. SIDOARJO'),
            array('id' => '3516','province_id' => '35','name' => 'KAB. MOJOKERTO'),
            array('id' => '3517','province_id' => '35','name' => 'KAB. JOMBANG'),
            array('id' => '3518','province_id' => '35','name' => 'KAB. NGANJUK'),
            array('id' => '3519','province_id' => '35','name' => 'KAB. MADIUN'),
            array('id' => '3520','province_id' => '35','name' => 'KAB. MAGETAN'),
            array('id' => '3521','province_id' => '35','name' => 'KAB. NGAWI'),
            array('id' => '3522','province_id' => '35','name' => 'KAB. BOJONEGORO'),
            array('id' => '3523','province_id' => '35','name' => 'KAB. TUBAN'),
            array('id' => '3524','province_id' => '35','name' => 'KAB. LAMONGAN'),
            array('id' => '3525','province_id' => '35','name' => 'KAB. GRESIK'),
            array('id' => '3526','province_id' => '35','name' => 'KAB. BANGKALAN'),
            array('id' => '3527','province_id' => '35','name' => 'KAB. SAMPANG'),
            array('id' => '3528','province_id' => '35','name' => 'KAB. PAMEKASAN'),
            array('id' => '3529','province_id' => '35','name' => 'KAB. SUMENEP'),
            array('id' => '3571','province_id' => '35','name' => 'KOTA KEDIRI'),
            array('id' => '3572','province_id' => '35','name' => 'KOTA BLITAR'),
            array('id' => '3573','province_id' => '35','name' => 'KOTA MALANG'),
            array('id' => '3574','province_id' => '35','name' => 'KOTA PROBOLINGGO'),
            array('id' => '3575','province_id' => '35','name' => 'KOTA PASURUAN'),
            array('id' => '3576','province_id' => '35','name' => 'KOTA MOJOKERTO'),
            array('id' => '3577','province_id' => '35','name' => 'KOTA MADIUN'),
            array('id' => '3578','province_id' => '35','name' => 'KOTA SURABAYA'),
            array('id' => '3579','province_id' => '35','name' => 'KOTA BATU'),
            array('id' => '3601','province_id' => '36','name' => 'KAB. PANDEGLANG'),
            array('id' => '3602','province_id' => '36','name' => 'KAB. LEBAK'),
            array('id' => '3603','province_id' => '36','name' => 'KAB. TANGERANG'),
            array('id' => '3604','province_id' => '36','name' => 'KAB. SERANG'),
            array('id' => '3671','province_id' => '36','name' => 'KOTA TANGERANG'),
            array('id' => '3672','province_id' => '36','name' => 'KOTA CILEGON'),
            array('id' => '3673','province_id' => '36','name' => 'KOTA SERANG'),
            array('id' => '3674','province_id' => '36','name' => 'KOTA TANGERANG SELATAN'),
            array('id' => '5101','province_id' => '51','name' => 'KAB. JEMBRANA'),
            array('id' => '5102','province_id' => '51','name' => 'KAB. TABANAN'),
            array('id' => '5103','province_id' => '51','name' => 'KAB. BADUNG'),
            array('id' => '5104','province_id' => '51','name' => 'KAB. GIANYAR'),
            array('id' => '5105','province_id' => '51','name' => 'KAB. KLUNGKUNG'),
            array('id' => '5106','province_id' => '51','name' => 'KAB. BANGLI'),
            array('id' => '5107','province_id' => '51','name' => 'KAB. KARANGASEM'),
            array('id' => '5108','province_id' => '51','name' => 'KAB. BULELENG'),
            array('id' => '5171','province_id' => '51','name' => 'KOTA DENPASAR'),
            array('id' => '5201','province_id' => '52','name' => 'KAB. LOMBOK BARAT'),
            array('id' => '5202','province_id' => '52','name' => 'KAB. LOMBOK TENGAH'),
            array('id' => '5203','province_id' => '52','name' => 'KAB. LOMBOK TIMUR'),
            array('id' => '5204','province_id' => '52','name' => 'KAB. SUMBAWA'),
            array('id' => '5205','province_id' => '52','name' => 'KAB. DOMPU'),
            array('id' => '5206','province_id' => '52','name' => 'KAB. BIMA'),
            array('id' => '5207','province_id' => '52','name' => 'KAB. SUMBAWA BARAT'),
            array('id' => '5208','province_id' => '52','name' => 'KAB. LOMBOK UTARA'),
            array('id' => '5271','province_id' => '52','name' => 'KOTA MATARAM'),
            array('id' => '5272','province_id' => '52','name' => 'KOTA BIMA'),
            array('id' => '5301','province_id' => '53','name' => 'KAB. KUPANG'),
            array('id' => '5302','province_id' => '53','name' => 'KAB TIMOR TENGAH SELATAN'),
            array('id' => '5303','province_id' => '53','name' => 'KAB. TIMOR TENGAH UTARA'),
            array('id' => '5304','province_id' => '53','name' => 'KAB. BELU'),
            array('id' => '5305','province_id' => '53','name' => 'KAB. ALOR'),
            array('id' => '5306','province_id' => '53','name' => 'KAB. FLORES TIMUR'),
            array('id' => '5307','province_id' => '53','name' => 'KAB. SIKKA'),
            array('id' => '5308','province_id' => '53','name' => 'KAB. ENDE'),
            array('id' => '5309','province_id' => '53','name' => 'KAB. NGADA'),
            array('id' => '5310','province_id' => '53','name' => 'KAB. MANGGARAI'),
            array('id' => '5311','province_id' => '53','name' => 'KAB. SUMBA TIMUR'),
            array('id' => '5312','province_id' => '53','name' => 'KAB. SUMBA BARAT'),
            array('id' => '5313','province_id' => '53','name' => 'KAB. LEMBATA'),
            array('id' => '5314','province_id' => '53','name' => 'KAB. ROTE NDAO'),
            array('id' => '5315','province_id' => '53','name' => 'KAB. MANGGARAI BARAT'),
            array('id' => '5316','province_id' => '53','name' => 'KAB. NAGEKEO'),
            array('id' => '5317','province_id' => '53','name' => 'KAB. SUMBA TENGAH'),
            array('id' => '5318','province_id' => '53','name' => 'KAB. SUMBA BARAT DAYA'),
            array('id' => '5319','province_id' => '53','name' => 'KAB. MANGGARAI TIMUR'),
            array('id' => '5320','province_id' => '53','name' => 'KAB. SABU RAIJUA'),
            array('id' => '5321','province_id' => '53','name' => 'KAB. MALAKA'),
            array('id' => '5371','province_id' => '53','name' => 'KOTA KUPANG'),
            array('id' => '6101','province_id' => '61','name' => 'KAB. SAMBAS'),
            array('id' => '6102','province_id' => '61','name' => 'KAB. MEMPAWAH'),
            array('id' => '6103','province_id' => '61','name' => 'KAB. SANGGAU'),
            array('id' => '6104','province_id' => '61','name' => 'KAB. KETAPANG'),
            array('id' => '6105','province_id' => '61','name' => 'KAB. SINTANG'),
            array('id' => '6106','province_id' => '61','name' => 'KAB. KAPUAS HULU'),
            array('id' => '6107','province_id' => '61','name' => 'KAB. BENGKAYANG'),
            array('id' => '6108','province_id' => '61','name' => 'KAB. LANDAK'),
            array('id' => '6109','province_id' => '61','name' => 'KAB. SEKADAU'),
            array('id' => '6110','province_id' => '61','name' => 'KAB. MELAWI'),
            array('id' => '6111','province_id' => '61','name' => 'KAB. KAYONG UTARA'),
            array('id' => '6112','province_id' => '61','name' => 'KAB. KUBU RAYA'),
            array('id' => '6171','province_id' => '61','name' => 'KOTA PONTIANAK'),
            array('id' => '6172','province_id' => '61','name' => 'KOTA SINGKAWANG'),
            array('id' => '6201','province_id' => '62','name' => 'KAB. KOTAWARINGIN BARAT'),
            array('id' => '6202','province_id' => '62','name' => 'KAB. KOTAWARINGIN TIMUR'),
            array('id' => '6203','province_id' => '62','name' => 'KAB. KAPUAS'),
            array('id' => '6204','province_id' => '62','name' => 'KAB. BARITO SELATAN'),
            array('id' => '6205','province_id' => '62','name' => 'KAB. BARITO UTARA'),
            array('id' => '6206','province_id' => '62','name' => 'KAB. KATINGAN'),
            array('id' => '6207','province_id' => '62','name' => 'KAB. SERUYAN'),
            array('id' => '6208','province_id' => '62','name' => 'KAB. SUKAMARA'),
            array('id' => '6209','province_id' => '62','name' => 'KAB. LAMANDAU'),
            array('id' => '6210','province_id' => '62','name' => 'KAB. GUNUNG MAS'),
            array('id' => '6211','province_id' => '62','name' => 'KAB. PULANG PISAU'),
            array('id' => '6212','province_id' => '62','name' => 'KAB. MURUNG RAYA'),
            array('id' => '6213','province_id' => '62','name' => 'KAB. BARITO TIMUR'),
            array('id' => '6271','province_id' => '62','name' => 'KOTA PALANGKARAYA'),
            array('id' => '6301','province_id' => '63','name' => 'KAB. TANAH LAUT'),
            array('id' => '6302','province_id' => '63','name' => 'KAB. KOTABARU'),
            array('id' => '6303','province_id' => '63','name' => 'KAB. BANJAR'),
            array('id' => '6304','province_id' => '63','name' => 'KAB. BARITO KUALA'),
            array('id' => '6305','province_id' => '63','name' => 'KAB. TAPIN'),
            array('id' => '6306','province_id' => '63','name' => 'KAB. HULU SUNGAI SELATAN'),
            array('id' => '6307','province_id' => '63','name' => 'KAB. HULU SUNGAI TENGAH'),
            array('id' => '6308','province_id' => '63','name' => 'KAB. HULU SUNGAI UTARA'),
            array('id' => '6309','province_id' => '63','name' => 'KAB. TABALONG'),
            array('id' => '6310','province_id' => '63','name' => 'KAB. TANAH BUMBU'),
            array('id' => '6311','province_id' => '63','name' => 'KAB. BALANGAN'),
            array('id' => '6371','province_id' => '63','name' => 'KOTA BANJARMASIN'),
            array('id' => '6372','province_id' => '63','name' => 'KOTA BANJARBARU'),
            array('id' => '6401','province_id' => '64','name' => 'KAB. PASER'),
            array('id' => '6402','province_id' => '64','name' => 'KAB. KUTAI KARTANEGARA'),
            array('id' => '6403','province_id' => '64','name' => 'KAB. BERAU'),
            array('id' => '6407','province_id' => '64','name' => 'KAB. KUTAI BARAT'),
            array('id' => '6408','province_id' => '64','name' => 'KAB. KUTAI TIMUR'),
            array('id' => '6409','province_id' => '64','name' => 'KAB. PENAJAM PASER UTARA'),
            array('id' => '6411','province_id' => '64','name' => 'KAB. MAHAKAM ULU'),
            array('id' => '6471','province_id' => '64','name' => 'KOTA BALIKPAPAN'),
            array('id' => '6472','province_id' => '64','name' => 'KOTA SAMARINDA'),
            array('id' => '6474','province_id' => '64','name' => 'KOTA BONTANG'),
            array('id' => '6501','province_id' => '65','name' => 'KAB. BULUNGAN'),
            array('id' => '6502','province_id' => '65','name' => 'KAB. MALINAU'),
            array('id' => '6503','province_id' => '65','name' => 'KAB. NUNUKAN'),
            array('id' => '6504','province_id' => '65','name' => 'KAB. TANA TIDUNG'),
            array('id' => '6571','province_id' => '65','name' => 'KOTA TARAKAN'),
            array('id' => '7101','province_id' => '71','name' => 'KAB. BOLAANG MONGONDOW'),
            array('id' => '7102','province_id' => '71','name' => 'KAB. MINAHASA'),
            array('id' => '7103','province_id' => '71','name' => 'KAB. KEPULAUAN SANGIHE'),
            array('id' => '7104','province_id' => '71','name' => 'KAB. KEPULAUAN TALAUD'),
            array('id' => '7105','province_id' => '71','name' => 'KAB. MINAHASA SELATAN'),
            array('id' => '7106','province_id' => '71','name' => 'KAB. MINAHASA UTARA'),
            array('id' => '7107','province_id' => '71','name' => 'KAB. MINAHASA TENGGARA'),
            array('id' => '7108','province_id' => '71','name' => 'KAB. BOLAANG MONGONDOW UTARA'),
            array('id' => '7109','province_id' => '71','name' => 'KAB. KEP. SIAU TAGULANDANG BIARO'),
            array('id' => '7110','province_id' => '71','name' => 'KAB. BOLAANG MONGONDOW TIMUR'),
            array('id' => '7111','province_id' => '71','name' => 'KAB. BOLAANG MONGONDOW SELATAN'),
            array('id' => '7171','province_id' => '71','name' => 'KOTA MANADO'),
            array('id' => '7172','province_id' => '71','name' => 'KOTA BITUNG'),
            array('id' => '7173','province_id' => '71','name' => 'KOTA TOMOHON'),
            array('id' => '7174','province_id' => '71','name' => 'KOTA KOTAMOBAGU'),
            array('id' => '7201','province_id' => '72','name' => 'KAB. BANGGAI'),
            array('id' => '7202','province_id' => '72','name' => 'KAB. POSO'),
            array('id' => '7203','province_id' => '72','name' => 'KAB. DONGGALA'),
            array('id' => '7204','province_id' => '72','name' => 'KAB. TOLI TOLI'),
            array('id' => '7205','province_id' => '72','name' => 'KAB. BUOL'),
            array('id' => '7206','province_id' => '72','name' => 'KAB. MOROWALI'),
            array('id' => '7207','province_id' => '72','name' => 'KAB. BANGGAI KEPULAUAN'),
            array('id' => '7208','province_id' => '72','name' => 'KAB. PARIGI MOUTONG'),
            array('id' => '7209','province_id' => '72','name' => 'KAB. TOJO UNA UNA'),
            array('id' => '7210','province_id' => '72','name' => 'KAB. SIGI'),
            array('id' => '7211','province_id' => '72','name' => 'KAB. BANGGAI LAUT'),
            array('id' => '7212','province_id' => '72','name' => 'KAB. MOROWALI UTARA'),
            array('id' => '7271','province_id' => '72','name' => 'KOTA PALU'),
            array('id' => '7301','province_id' => '73','name' => 'KAB. KEPULAUAN SELAYAR'),
            array('id' => '7302','province_id' => '73','name' => 'KAB. BULUKUMBA'),
            array('id' => '7303','province_id' => '73','name' => 'KAB. BANTAENG'),
            array('id' => '7304','province_id' => '73','name' => 'KAB. JENEPONTO'),
            array('id' => '7305','province_id' => '73','name' => 'KAB. TAKALAR'),
            array('id' => '7306','province_id' => '73','name' => 'KAB. GOWA'),
            array('id' => '7307','province_id' => '73','name' => 'KAB. SINJAI'),
            array('id' => '7308','province_id' => '73','name' => 'KAB. BONE'),
            array('id' => '7309','province_id' => '73','name' => 'KAB. MAROS'),
            array('id' => '7310','province_id' => '73','name' => 'KAB. PANGKAJENE KEPULAUAN'),
            array('id' => '7311','province_id' => '73','name' => 'KAB. BARRU'),
            array('id' => '7312','province_id' => '73','name' => 'KAB. SOPPENG'),
            array('id' => '7313','province_id' => '73','name' => 'KAB. WAJO'),
            array('id' => '7314','province_id' => '73','name' => 'KAB. SIDENRENG RAPPANG'),
            array('id' => '7315','province_id' => '73','name' => 'KAB. PINRANG'),
            array('id' => '7316','province_id' => '73','name' => 'KAB. ENREKANG'),
            array('id' => '7317','province_id' => '73','name' => 'KAB. LUWU'),
            array('id' => '7318','province_id' => '73','name' => 'KAB. TANA TORAJA'),
            array('id' => '7322','province_id' => '73','name' => 'KAB. LUWU UTARA'),
            array('id' => '7324','province_id' => '73','name' => 'KAB. LUWU TIMUR'),
            array('id' => '7326','province_id' => '73','name' => 'KAB. TORAJA UTARA'),
            array('id' => '7371','province_id' => '73','name' => 'KOTA MAKASSAR'),
            array('id' => '7372','province_id' => '73','name' => 'KOTA PARE PARE'),
            array('id' => '7373','province_id' => '73','name' => 'KOTA PALOPO'),
            array('id' => '7401','province_id' => '74','name' => 'KAB. KOLAKA'),
            array('id' => '7402','province_id' => '74','name' => 'KAB. KONAWE'),
            array('id' => '7403','province_id' => '74','name' => 'KAB. MUNA'),
            array('id' => '7404','province_id' => '74','name' => 'KAB. BUTON'),
            array('id' => '7405','province_id' => '74','name' => 'KAB. KONAWE SELATAN'),
            array('id' => '7406','province_id' => '74','name' => 'KAB. BOMBANA'),
            array('id' => '7407','province_id' => '74','name' => 'KAB. WAKATOBI'),
            array('id' => '7408','province_id' => '74','name' => 'KAB. KOLAKA UTARA'),
            array('id' => '7409','province_id' => '74','name' => 'KAB. KONAWE UTARA'),
            array('id' => '7410','province_id' => '74','name' => 'KAB. BUTON UTARA'),
            array('id' => '7411','province_id' => '74','name' => 'KAB. KOLAKA TIMUR'),
            array('id' => '7412','province_id' => '74','name' => 'KAB. KONAWE KEPULAUAN'),
            array('id' => '7413','province_id' => '74','name' => 'KAB. MUNA BARAT'),
            array('id' => '7414','province_id' => '74','name' => 'KAB. BUTON TENGAH'),
            array('id' => '7415','province_id' => '74','name' => 'KAB. BUTON SELATAN'),
            array('id' => '7471','province_id' => '74','name' => 'KOTA KENDARI'),
            array('id' => '7472','province_id' => '74','name' => 'KOTA BAU BAU'),
            array('id' => '7501','province_id' => '75','name' => 'KAB. GORONTALO'),
            array('id' => '7502','province_id' => '75','name' => 'KAB. BOALEMO'),
            array('id' => '7503','province_id' => '75','name' => 'KAB. BONE BOLANGO'),
            array('id' => '7504','province_id' => '75','name' => 'KAB. POHUWATO'),
            array('id' => '7505','province_id' => '75','name' => 'KAB. GORONTALO UTARA'),
            array('id' => '7571','province_id' => '75','name' => 'KOTA GORONTALO'),
            array('id' => '7601','province_id' => '76','name' => 'KAB. PASANGKAYU'),
            array('id' => '7602','province_id' => '76','name' => 'KAB. MAMUJU'),
            array('id' => '7603','province_id' => '76','name' => 'KAB. MAMASA'),
            array('id' => '7604','province_id' => '76','name' => 'KAB. POLEWALI MANDAR'),
            array('id' => '7605','province_id' => '76','name' => 'KAB. MAJENE'),
            array('id' => '7606','province_id' => '76','name' => 'KAB. MAMUJU TENGAH'),
            array('id' => '8101','province_id' => '81','name' => 'KAB. MALUKU TENGAH'),
            array('id' => '8102','province_id' => '81','name' => 'KAB. MALUKU TENGGARA'),
            array('id' => '8103','province_id' => '81','name' => 'KAB. KEPULAUAN TANIMBAR'),
            array('id' => '8104','province_id' => '81','name' => 'KAB. BURU'),
            array('id' => '8105','province_id' => '81','name' => 'KAB. SERAM BAGIAN TIMUR'),
            array('id' => '8106','province_id' => '81','name' => 'KAB. SERAM BAGIAN BARAT'),
            array('id' => '8107','province_id' => '81','name' => 'KAB. KEPULAUAN ARU'),
            array('id' => '8108','province_id' => '81','name' => 'KAB. MALUKU BARAT DAYA'),
            array('id' => '8109','province_id' => '81','name' => 'KAB. BURU SELATAN'),
            array('id' => '8171','province_id' => '81','name' => 'KOTA AMBON'),
            array('id' => '8172','province_id' => '81','name' => 'KOTA TUAL'),
            array('id' => '8201','province_id' => '82','name' => 'KAB. HALMAHERA BARAT'),
            array('id' => '8202','province_id' => '82','name' => 'KAB. HALMAHERA TENGAH'),
            array('id' => '8203','province_id' => '82','name' => 'KAB. HALMAHERA UTARA'),
            array('id' => '8204','province_id' => '82','name' => 'KAB. HALMAHERA SELATAN'),
            array('id' => '8205','province_id' => '82','name' => 'KAB. KEPULAUAN SULA'),
            array('id' => '8206','province_id' => '82','name' => 'KAB. HALMAHERA TIMUR'),
            array('id' => '8207','province_id' => '82','name' => 'KAB. PULAU MOROTAI'),
            array('id' => '8208','province_id' => '82','name' => 'KAB. PULAU TALIABU'),
            array('id' => '8271','province_id' => '82','name' => 'KOTA TERNATE'),
            array('id' => '8272','province_id' => '82','name' => 'KOTA TIDORE KEPULAUAN'),
            array('id' => '9103','province_id' => '91','name' => 'KAB. JAYAPURA'),
            array('id' => '9105','province_id' => '91','name' => 'KAB. KEPULAUAN YAPEN'),
            array('id' => '9106','province_id' => '91','name' => 'KAB. BIAK NUMFOR'),
            array('id' => '9110','province_id' => '91','name' => 'KAB. SARMI'),
            array('id' => '9111','province_id' => '91','name' => 'KAB. KEEROM'),
            array('id' => '9115','province_id' => '91','name' => 'KAB. WAROPEN'),
            array('id' => '9119','province_id' => '91','name' => 'KAB. SUPIORI'),
            array('id' => '9120','province_id' => '91','name' => 'KAB. MAMBERAMO RAYA'),
            array('id' => '9171','province_id' => '91','name' => 'KOTA JAYAPURA'),
            array('id' => '9201','province_id' => '92','name' => 'KAB. SORONG'),
            array('id' => '9202','province_id' => '92','name' => 'KAB. MANOKWARI'),
            array('id' => '9203','province_id' => '92','name' => 'KAB. FAK FAK'),
            array('id' => '9204','province_id' => '92','name' => 'KAB. SORONG SELATAN'),
            array('id' => '9205','province_id' => '92','name' => 'KAB. RAJA AMPAT'),
            array('id' => '9206','province_id' => '92','name' => 'KAB. TELUK BINTUNI'),
            array('id' => '9207','province_id' => '92','name' => 'KAB. TELUK WONDAMA'),
            array('id' => '9208','province_id' => '92','name' => 'KAB. KAIMANA'),
            array('id' => '9209','province_id' => '92','name' => 'KAB. TAMBRAUW'),
            array('id' => '9210','province_id' => '92','name' => 'KAB. MAYBRAT'),
            array('id' => '9211','province_id' => '92','name' => 'KAB. MANOKWARI SELATAN'),
            array('id' => '9212','province_id' => '92','name' => 'KAB. PEGUNUNGAN ARFAK'),
            array('id' => '9271','province_id' => '92','name' => 'KOTA SORONG'),
            array('id' => '9301','province_id' => '93','name' => 'KAB. MERAUKE'),
            array('id' => '9302','province_id' => '93','name' => 'KAB. BOVEN DIGOEL'),
            array('id' => '9303','province_id' => '93','name' => 'KAB. MAPPI'),
            array('id' => '9304','province_id' => '93','name' => 'KAB. ASMAT'),
            array('id' => '9401','province_id' => '94','name' => 'KAB. NABIRE'),
            array('id' => '9402','province_id' => '94','name' => 'KAB. PUNCAK JAYA'),
            array('id' => '9403','province_id' => '94','name' => 'KAB. PANIAI'),
            array('id' => '9404','province_id' => '94','name' => 'KAB. MIMIKA'),
            array('id' => '9405','province_id' => '94','name' => 'KAB. PUNCAK'),
            array('id' => '9406','province_id' => '94','name' => 'KAB. DOGIYAI'),
            array('id' => '9407','province_id' => '94','name' => 'KAB. INTAN JAYA'),
            array('id' => '9408','province_id' => '94','name' => 'KAB. DEIYAI'),
            array('id' => '9501','province_id' => '95','name' => 'KAB. JAYAWIJAYA'),
            array('id' => '9502','province_id' => '95','name' => 'KAB. PEGUNUNGAN BINTANG'),
            array('id' => '9503','province_id' => '95','name' => 'KAB. YAHUKIMO'),
            array('id' => '9504','province_id' => '95','name' => 'KAB. TOLIKARA'),
            array('id' => '9505','province_id' => '95','name' => 'KAB. MAMBERAMO TENGAH'),
            array('id' => '9506','province_id' => '95','name' => 'KAB. YALIMO'),
            array('id' => '9507','province_id' => '95','name' => 'KAB. LANNY JAYA'),
            array('id' => '9508','province_id' => '95','name' => 'KAB. NDUGA')
        ];

        foreach ($regencies as $regencie) {
            DB::table('reg_regencies')->insert($regencie);
        }
    }
}
